; PlatformIO Project Configuration File
;
; https://docs.platformio.org/page/projectconf.html

[platformio]
test_dir = tests

[env:spi_raw_demo]
platform = espressif32
board = adafruit_qtpy_esp32
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyACM1
monitor_port = /dev/ttyACM1
build_src_filter = -<*> +<../demos/spi_raw_demo.cpp>
